Lifecycle script improvements (#229)
This branch makes a number of improvements to the scripts for the 
lifecycle example, primarily based on changes I found useful while
using this example for testing.

In particular:

* `bin/deploy` now takes an optional `--ctrl-prefix` flag to
  configure the prefix added to the name of the Linkerd control
  plane namespace. This is sometimes valuable when running multiple
  lifecycle tests in the same cluster.
* `bin/deploy`, `bin/scale`, and `bin/teardown` all take an optional
  `--ns-prefix` flag that configures the prefix added to the Linkerd
  namespaces created or modified by the script.
* `bin/teardown` now deletes all namespaces with one `kubectl delete`
  command. This is because `kubectl` was recently changed so that the
  delete command will block until the resource is deleted, so running
  multiple `kubectl delete`s in parallel takes much longer than it did
  previously. The script now tries to delete the namespaces in parallel.
* `bin/deploy` now allows arbitrary arguments to be passed to the 
  `linkerd inject` command. This is valuable when testing a version of
  the Linkerd proxy other than the one that `inject` uses by default,
  when a more verbose proxy log level is desired for debugging, and
  so on.
* All scripts now print usage messages when provided with unrecognizable
  arguments.
* Fixed some `shellcheck` lints.

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

diff --git a/lifecycle/bin/scale b/lifecycle/bin/scale
--- a/lifecycle/bin/scale
+++ b/lifecycle/bin/scale
@@ -2,12 +2,60 @@
 
 set -e
 
-NAMESPACES=${1:-1}
-REPLICAS=${2:-1}
+usage() {
+  cat <<EOM
+Usage: $0 [NAMESPACES] [REPLICAS] [options]
 
-function scale() {
+Arguments:
+  NAMESPACES                The number of namespaces to scale. [default 1]
+  REPLICAS                  The desired number of replicas to scale to [default 1]
+
+Options:
+  -n, --ns-prefix <PREFIX>  The prefix of the namespaces to scale. [default 'lifecycle']
+  -h, --help                Show this message.
+EOM
+}
+
+NAMESPACES=1
+REPLICAS=1
+NS_PREFIX="lifecycle"
+NUM_NUMERICS=0
+
+while [ "$1" != "" ]; do
+  case $1 in
+    -h | --help)
+      usage
+      exit 0
+      ;;
+    -n | --ns-prefix)
+      shift
+      NS_PREFIX="${1:-$NS_PREFIX}"
+      ;;
+    *[!0-9]*)
+      echo "Error: Unknown argument '$1'" >&2
+      usage
+      exit 1
+      ;;
+    *)
+      case "$NUM_NUMERICS" in
+        0) NAMESPACES="$1"
+           ;;
+        1) REPLICAS="$1"
+           ;;
+        *) echo "Error: Too many numeric arguments (expected a maximum of 2)" >&2
+           usage
+           exit 1
+           ;;
+      esac
+      NUM_NUMERICS=$(($NUM_NUMERICS + 1))
+      ;;
+  esac
+  shift
+done
+
+scale() {
   echo "\nScaling $1 to $REPLICAS replicas..."
-  kubectl -n $1 scale --replicas=$REPLICAS deploy/bb-broadcast deploy/bb-p2p deploy/bb-terminus
+  kubectl -n "$1" scale --replicas="$REPLICAS" deploy/bb-broadcast deploy/bb-p2p deploy/bb-terminus
 }
 
 if [ "$NAMESPACES" -gt 100 ]; then
@@ -22,9 +70,9 @@ fi
 
 echo "Scaling $NAMESPACES injected, TLS, and baseline namespaces to $REPLICAS replicas..."
 
-for i in `seq 1 $NAMESPACES`;
+for i in $(seq 1 "$NAMESPACES");
 do
-  NS=lifecycle$i
+  NS="$NS_PREFIX""$i"
 
   scale "$NS"
   scale "$NS-tls"
